[env:cardputer_adv]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = components
lib_ldf_mode = deep
lib_deps =
  t-vk/ESP32 BLE Keyboard@^0.3.2
  ESP32 BLE Mouse
build_unflags =
  -std=gnu++11
  -std=gnu++14
build_flags =
  -std=gnu++17
  -Isrc
  -Isrc/hal
  -Isrc/apps
  -Isrc/assets
  -Icomponents/mooncake/src
  -Icomponents/mooncake_log/src
  -Icomponents/smooth_ui_toolkit/src
  -Icomponents/M5Unified/src
  -Icomponents/M5GFX/src
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/tinyusb
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCONFIG_TINYUSB_ENABLED=1
  -DCONFIG_TINYUSB_HID_ENABLED=1
  -DCONFIG_TINYUSB_MSC_ENABLED=1
board_build.partitions = partitions.csv
board_build.flash_size = 8MB
monitor_speed = 115200
build_src_filter =
  +<*>
  -<apps/app_repl/app_repl.*>
  -<apps/app_repl/PikaScript/*>
  -<hal/utils/ir_nec/*>
  -<hal/cap_lora868/cap_lora868.cpp>
  -<hal/cap_lora868/radio_lib/*>
  -<hal/cap_lora868/uart/*>
  -<hal/utils/ble_hid_device/*>
